spring.application.name=order_status_log_service
server.port=8094

#Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/order_status_log_db
spring.datasource.username=root
spring.datasource.password=Deeksha06**

#JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect